### PR TITLE
Update AutoPublisher.py

### PR DESCRIPTION
**Pull request by SightedBike273**
Fixed the bot
* the bot can now identify news channels 
* the bot actually can go online now

comments are in the file to explain what things do.

### CODE REVIEW

**Comment by imightknoiw** [comment]
why

**Comment by SightedBike273** [comment]
> why

why what?

**Comment by imightknoiw** [comment]
old repo, why fix lol

**Comment by SightedBike273** [comment]
I committed the changes on 18/11/22. The last commit to the repo was on 13/11/22. It was not old when I fixed it.

**Pull request closed without merging**
